CREATE TABLE PROJ (
    PROJID            SMALLINT(3) NOT NULL,
    PROJNAME          CHAR(5),
    BUDGET            FLOAT(2),
PRIMARY KEY (PROJID));

INSERT INTO PROJ VALUES (101, "ALPHA", 96000);
INSERT INTO PROJ VALUES (102, "BETA", 82000);
INSERT INTO PROJ VALUES (103, "GAMMA", 15000);

